<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { getPercentColor } from '$lib/utils';
	type Progress = Record<number, { attempted: number; earnedPoints: number; possiblePoints: number; percentage: number }>;
	let progress = $state<Progress>({}); let active = $state<{ sessionId: string; type: string; answeredCount: number; totalQuestions: number; deadlineAt?: string } | null>(null);
	onMount(async () => { const response = await fetch('/api/progress'); if (response.ok) { const data = await response.json(); progress = data.progress; active = data.activeSession; } });
	async function abandon() { if (!active) return; await fetch(`/api/quiz/session/${active.sessionId}`, { method: 'DELETE' }); active = null; }
	function open(type: 'quiz' | 'scenario' | 'pbq' | 'full') { goto(type === 'full' ? '/quiz?start=1&type=full&mode=exam' : `/${type === 'quiz' ? 'quiz' : type === 'scenario' ? 'scenarios' : 'pbq'}?start=1`); }
</script>
<div class="space-y-8"><section class="py-6 text-center"><h1 class="gradient-text text-4xl font-extrabold">Security+ Practice Lab</h1><p class="mt-2 text-slate-400">Original objective-aligned MCQs and multi-format PBQs.</p></section>
{#if active}<section class="glass flex items-center justify-between rounded-xl p-4"><div><strong class="text-white">Active {active.type} session</strong><p class="text-sm text-slate-400">{active.answeredCount}/{active.totalQuestions} answered</p></div><div class="flex gap-2"><button class="rounded bg-cyan-600 px-3 py-2" onclick={() => goto(`/quiz?session=${active?.sessionId}`)}>Resume</button><button class="rounded bg-slate-700 px-3 py-2" onclick={abandon}>Abandon</button></div></section>{/if}
<section class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><button class="rounded-xl bg-cyan-700 p-5 text-left" onclick={() => open('quiz')}>Objective Quiz<br /><span class="text-sm text-cyan-100">20 multiple-choice</span></button><button class="rounded-xl bg-purple-700 p-5 text-left" onclick={() => open('scenario')}>Scenario Quiz<br /><span class="text-sm text-purple-100">10 scenarios</span></button><button class="rounded-xl bg-orange-700 p-5 text-left" onclick={() => open('pbq')}>PBQ Practice<br /><span class="text-sm text-orange-100">5 PBQs</span></button><button class="rounded-xl bg-yellow-700 p-5 text-left" onclick={() => open('full')}>Start 90-question practice exam<br /><span class="text-sm text-yellow-100">85 multiple-choice + 5 PBQs · 90 minutes</span></button></section>
<section><h2 class="mb-3 text-xl font-bold text-white">Domain progress</h2><div class="grid gap-3 sm:grid-cols-5">{#each [1,2,3,4,5] as domain}<div class="glass rounded-xl p-4"><p class="text-white">Domain {domain}</p><p class="text-2xl font-bold {getPercentColor(progress[domain]?.percentage ?? 0)}">{progress[domain]?.percentage ?? 0}%</p><p class="text-sm text-slate-400">{progress[domain]?.earnedPoints ?? 0}/{progress[domain]?.possiblePoints ?? 0} points</p></div>{/each}</div></section></div>
